include:
  - board: nice_nano_v2
    shield: lily58_left nice_view_adapter nice_view
    artifact-name: lily58_left
    snippet: studio-rpc-usb-uart  

  - board: nice_nano_v2
    shield: lily58_right nice_view_adapter nice_view
    artifact-name: lily58_right
    snippet: studio-rpc-usb-uart
