# GitHub Actions build matrix for Lily58 with dual Nice!View

include:
  # Left half (central) with USB logging
  - board: nice_nano_v2
    shield: lily58_left nice_view_adapter nice_view
    artifact-name: lily58_left
    snippet: studio-rpc-usb-uart

  # Right half (peripheral) without USB logging
  - board: nice_nano_v2
    shield: lily58_right nice_view_adapter nice_view
    artifact-name: lily58_right
    snippet: studio-rpc-usb-uart
